language: haskell

ghc:
  - 7.6.3
  - 7.8.4

before_install:
  - cabal install cabal-install
  - export PATH=$HOME/.cabal/bin:$PATH
  - cabal --version

install:
  - cabal update
  - cabal install -j --only-dependencies

script:
  - cabal configure
  - cabal build
